version: "2"

mem_limit: 128000000
cpu_limit: 1

services:
  proxy:
    image: akkerman/todo-proxy
    container_name: "todo-proxy"
    ports:
      - "80:80"

  node:
    image: akkerman/todo-node
    container_name: "todo-node"

  python:
    image: akkerman/todo-python
    container_name: "todo-python"
    command: python -u app.py

  mongo:
    image: mongo:3.0.2
    container_name: "todo-mongo"
