---
version: "3"

services:
  proxy:
    build: ./proxy/
    image: 192.168.20.1:5000/todo_proxy
    container_name: todo_proxy
    ports:
      - "8080:8080"
    depends_on:
      - node
      - python

  node:
    build: ./node
    image: 192.168.20.1:5000/todo_node
    container_name: todo_node
    environment:
      - system=xtron
    depends_on:
      - mongo

  python:
    build: ./python
    image: 192.168.20.1:5000/todo_python
    container_name: todo_python
    command: python -u app.py
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0.2
    container_name: todo_mongo
    deploy:
      resources:
        limits:
          memory: 500M
