version: "2"

services:
  proxy:
    build: ./proxy/
    container_name: "bakjes"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - bus

  node:
    build: ./node
    container_name: "bakjes-node"
    restart: always
    networks:
      - bus

  python:
    build: ./python
    container_name: "bakjes-python"
    command: python -u app.py
    networks:
      - bus

  mongo:
    image: mongo:3.0.2
    container_name: "bakjes-mongo"
    restart: always
    networks:
      - bus

networks:
  bus:
    driver: bridge



